all: 	exploration_dilatation explorationPartielle explorationNaif explorationLargeur algo_CFC

exploration_dilatation:	exploration_dilatation.c graphes.c graphes.h
	gcc exploration_dilatation.c graphes.c -o exploration_dilatation

explorationPartielle:	explorationPartielle.c graphes.c graphes.h
	gcc explorationPartielle.c graphes.c -o explorationPartielle

explorationNaif: explorationNaif.c graphes.c graphes.h
	gcc explorationNaif.c graphes.c -o explorationNaif

explorationLargeur: explorationLargeur.c graphes.c graphes.h
	gcc explorationLargeur.c graphes.c -o explorationLargeur
	
algo_CFC: algo_CFC.c graphes.c graphes.h
	gcc algo_CFC.c graphes.c -o algo_CFC